<?php
require_once('../tcpdf/tcpdf.php');
require('../connection.php');
$seller=$_SESSION['sellerid'];
$sql="SELECT 
p.product_id,
p.product_name,
SUM(o.quantity) AS total_quantity_sold,
SUM(o.quantity * o.unit_price) AS total_revenue
FROM 
order_tbl o
JOIN 
product p ON o.product_id = p.product_id
WHERE 
p.seller_id = <seller_id>
GROUP BY 
p.product_id, p.product_name";

$pdf = new TCPDF();
$pdf->SetTitle('My PDF Document');
$pdf->SetAuthor('John Doe');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 12);
$html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1, h2, h3 {
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Sales Report</h1>
        <p>Date: <?php echo date("Y-m-d"); ?></p>
        
        <h2>Overall Sales Summary</h2>
        <table>
            <thead>
                <tr>
                    <th>Month</th>
                    <th>Total Sales</th>
                </tr>
            </thead>
            <tbody>
                <!-- Loop through sales data to populate table rows -->
                <tr>
                    <td>January</td>
                    <td>$1000</td>
                </tr>
                <!-- Add more rows as needed -->
            </tbody>
        </table>

        <h2>Product-wise Sales</h2>
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity Sold</th>
                    <th>Total Revenue</th>
                </tr>
            </thead>
            <tbody>
                <!-- Loop through product sales data to populate table rows -->
                <tr>
                    <td>Product A</td>
                    <td>100</td>
                    <td>$500</td>
                </tr>
                <!-- Add more rows as needed -->
            </tbody>
        </table>

        <div class="footer">
            Generated by YourCompany &bull; <?php echo date("Y"); ?>
        </div>
    </div>
</body>
</html>
';
$pdf->writeHTML($html, true, false, true, false, '');
// Output PDF to the browser
$pdf->Output('example.pdf', 'I');

// Save PDF to a file
// $pdf->Output('example.pdf', 'F');

?>
