<?php
require_once('../tcpdf/tcpdf.php');
require('../connection.php');

$seller = $_SESSION['sellerid'];

$sql = "SELECT s.*, r.email AS role_email
        FROM tbl_seller_register s
        JOIN tbl_role r ON s.role_id = r.role_id
        WHERE s.role_id = $seller";
$all_seller = $conn->query($sql);
while ($row = mysqli_fetch_assoc($all_seller)) {
    $sellerName = $row['seller_name'];
    $sellerMobile = $row['seller_mobile'];
    $sellerEmail = $row['role_email'];
    $company = $row['company'];
}
$sql_report="SELECT 
p.product_id,
p.product_name,
SUM(o.quantity) AS total_quantity_sold,
SUM(o.quantity * o.unit_price) AS total_revenue
FROM 
tbl_order o
JOIN 
tbl_product p ON o.product_id = p.product_id
WHERE 
p.seller_id = $seller
GROUP BY 
p.product_id, p.product_name";

$report=$conn->query($sql_report);
$sql_monthly_report = "SELECT 
                            MONTH(o.order_date) AS month,
                            SUM(o.quantity * o.unit_price) AS total_revenue
                        FROM 
                            tbl_order o
                        JOIN 
                            tbl_product p ON o.product_id = p.product_id
                        WHERE 
                            p.seller_id = $seller
                        GROUP BY 
                            MONTH(o.order_date)";

$result_monthly_report = $conn->query($sql_monthly_report);

// Create new TCPDF instance
$pdf = new TCPDF();
$pdf->SetTitle('My PDF Document');
$pdf->SetAuthor('John Doe');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 12);

// Generate HTML content
$html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1, h2, h3 {
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Sales Report</h1>
        <p>Date: ' . date("Y-m-d") . '</p>
        
        <h2>Overall Sales Summary</h2>
        <table>
            <thead>
                <tr>
                    <th>Month</th>
                    <th>Total Sales</th>
                </tr>
            </thead>
            <tbody>';

// Loop through monthly report data to populate table rows
while ($row = mysqli_fetch_assoc($result_monthly_report)) {
    $html .= '<tr>
                <td>' . date("F", mktime(0, 0, 0, $row["month"], 1)) . '</td>
                <td>' . $row["total_revenue"] . '</td>
            </tr>';
}

$html .= '</tbody>
        </table>

        <h2>Product-wise Sales</h2>
        <table>
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity Sold</th>
                    <th>Total Revenue</th>
                </tr>
            </thead>
            <tbody>
                <!-- Loop through product sales data to populate table rows -->';
               
                while ($row = mysqli_fetch_assoc($report)) {
    $html .= '<tr>
                <td>' . $row['product_name'] . '</td>
                <td>' . $row['total_quantity_sold'] . '</td>
                <td>' . $row['total_revenue'] . '</td>
            </tr>';
}

                $html .='    <!-- Add more rows as needed -->
            </tbody>
        </table>

        <div class="footer">
            Generated by YourCompany &bull; ' . date("Y") . '
        </div>
    </div>
</body>
</html>';

// Write HTML content to PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Output PDF to the browser
$pdf->Output('example.pdf', 'I');
?>
